### ISSUE TITLE
Laser Bug

### ISSUE THREAD

**Issue by Defcon9999999** [pdcook/PCE#4]
Found a bug for the  mod, was playing earlier with Time To Grind and notice no one got laser the entire day, when I went intoSand box Mode later in the day I notice when ever I type in Laser I got Last Stand instead. 
![20210707222410_1](https://user-images.githubusercontent.com/87107970/124858401-96d97980-df73-11eb-870e-5b0c3717f82c.jpg)

**Comment by pdcook** [comment]
Read changelog in README, specifically notes for v0.2.0.2.
